name: Unit Testing

on:
  push:
    branches: [main]
  pull_request:

jobs:
  flake8:
    name: "Linter"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install flake8
      - name: Lint with flake8
        run: |
          flake8 --max-complexity=10 --max-line-length=99 --show-source --statistics

  mypy:
    name: "Static Type Checker"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          sudo apt update -y
          sudo apt -y install mypy
      - name: Check with MyPy
        run: |
          mypy --strict .
